# Generated by Django 5.0.1 on 2024-07-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
